package LNZModule;

enum ProgramState {
  INITIAL_INTERFACE, EXITING, ENTERING_MAINMENU, MAINMENU_INTERFACE,
  ENTERING_MAPEDITOR, MAPEDITOR_INTERFACE, ENTERING_TUTORIAL, TUTORIAL,
  ENTERING_PLAYING, PLAYING, ENTERING_MINIGAMES, MINIGAMES;
}